tschaub/mock-fs

.travis.yml
changelog.md
readme.md

This adds docs and adds 0.12 to the list for Travis.

Document support for Node 0.12

---

.travis.yml
lib/index.js
node/fs-1.1.0.js

* Added a check on the possibility of overwriting property for replace `realFs`. This was done due to the fact that mode fields in `fs` were protected from accidental overwriting: https://github.com/iojs/io.js/blob/v1.1.0/lib/fs.js#L164-L168.
* Changed the [binding declaration](https://github.com/iojs/io.js/blob/v1.x/lib/fs.js#L9) in the source code: use `var`. This was done due to the fact that in `fs` was used `const` to define constants: https://github.com/iojs/io.js/commit/86eda173b16b6ece9712e066661a0ac5db6795e8.

Added support for io.js

---

appveyor.yml

To run tests in Windows OS on every Pull Request or commit as well as using the Travis need use [AppVeyor](http://www.appveyor.com/).
For this need to add configuration file `appveyor.yml` and add `mock-fs` to your projects in AppVeyor.
More read in [docs](http://www.appveyor.com/docs).

Run tests in Windows OS

---

lib/filesystem.js
lib/item.js
readme.md
test/lib/binding.spec.js
test/lib/item.spec.js

In issue #31 I reported that since node 0.11 the ```fs.Stats``` call would return a ```birthtime``` property that specified the initial creation time of the item.
This patch seems to match existing behavior where the virtual file system matches that of the latest version of node regardless of which version of node it is actually running on (for example, Stats always returns a blksize which was also only introduced in 0.11).
Thanks,

Add support for birthtime

---

lib/index.js
test/lib/index.spec.js

Hi there - thanks for a great library!
The only problem I had with it was that the `process.cwd()` and `process.chdir()` methods still act on the real filesystem, rather than the mock filesystem. This pull request means that these methods get mocked along with the filesystem bindings, ensuring that `process` is kept in sync with `fs`.
A couple of points to note:
- I've tried to match the code style to what's around it, but let me know if there's any formatting/naming/etc conventions that I've missed
- I'm pretty new to testing so I'm not sure how well I've written the tests
Let me know if this is all ok!

Mock process.cwd and process.chdir methods

---

readme.md

Changes:
1. Added some h3 to split up caveats section
2. Added note about mock-fs not working with graceful-fs 3.0.0+ and gulp 3.7.0+
As far as I can tell gulp 3.6.x works fine with mock-fs.
- In [gulp 3.7.0](https://github.com/gulpjs/gulp/commit/2ae97419ad69c279b3e98533992aa9b9f3e6853e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) the dep on vinyl-fs changed from `^0.1.3` to `^0.2.0`.
- In [vinyl-fs 0.2.1](https://github.com/wearefractal/vinyl-fs/commit/c9b2c075dbb55ee97cd6ab9909bd1e1f87bf77e0) the dep on graceful-fs changed from `^2.0.1` to `^3.0.0`.
- graceful-fs 3.0.0 is where compatibility broke
Relevant issues: #42, #44

Add blurb to readme re: graceful-fs and gulp compat

---

readme.md

:tada:
P.s. #42 is outdated too.

Mock-fs is compatible with graceful-fs ^4

---

lib/binding.js
lib/filesystem.js
test/lib/binding.spec.js

Follow symlinks in readdir() and readdirSync()

---

package.json

Rewire 2.3 handles globals better so that babel can compile it. https://github.com/jhnns/rewire/releases/tag/v2.3.0

update rewire to 2.3.4 to allow for babel compilation

---

lib/binding.js
lib/filesystem.js
test/lib/binding.spec.js
test/lib/filesystem.spec.js

Further adjustment to this feature to make links to links work
correctly (at least for readdir and FS.getItem)

Handle links to symlinks in FileSystem#getItem()

---

.travis.yml
lib/index.js
node/fs-4.0.0.js

The comments in #59 indicate that there are no changes between io.js 3.x and node 4.x, thought a PR might be accepted that uses the logic from io.js 3.x.
All the tests are passing in travis for Node v4.2 in travis.

Add support for node v4.x Closes: #59

---

lib/index.js
node/fs-5.0.0.js

This adds node v5 compatibility to mock-fs. Fixes #67
The `node/fs-5.0.0.js` is the same as https://github.com/nodejs/node/blob/v5.x/lib/fs.js except:
```diff
--- v5.js	2015-11-28 20:45:32.000000000 -0500
+++ node/fs-5.0.0.js	2015-11-28 20:43:23.000000000 -0500
@@ -7,8 +7,8 @@
const util = require('util');
const pathModule = require('path');
-const binding = process.binding('fs');
-const constants = require('constants');
+var binding = process.binding('fs');
+const constants = process.binding('constants');
const fs = exports;
const Buffer = require('buffer').Buffer;
const Stream = require('stream').Stream;
@@ -250,7 +250,7 @@
context.isUserFd = isFd(path); // file descriptor ownership
var req = new FSReqWrap();
req.context = context;
-  req.oncomplete = readFileAfterOpen;
+ …
```

Add node v5.x compatibility

---

lib/filesystem.js
lib/index.js
readme.md
test/lib/filesystem.spec.js
test/lib/index.spec.js

By default, `process.cwd()` and `os.tmpdir()` are created for new mock filesystems.  To change this behavior, `createCwd` and `createTmp` options can be passed.
E.g.
```js
// mock the filesystem without creating process.cwd()
mock({'/one': 'file contents'}, {createCwd: false});
```
```js
// mock the filesystem without creating os.tmpdir()
mock({file: 'contents'}, {createTmp: false});
```
Fixes #71.

Add options for creating cwd and tmp directories

---

test/lib/index.spec.js

Thanks @shyiko for the addition of `binding.access()` (see #78).  This adds tests for `fs.access()` and `fs.accessSync()`.
Fixes #79.

Tests for fs.access() and fs.accessSync()

---

lib/binding.js
test/lib/index.spec.js

There are several cases WRT the permissions of parent directories where `mock-fs` doesn't accurately mirror a real filesystem's behaviour. This PR highlights and fixes a few of them, in `mkdir` and `rmdir` and their synchronous counterparts. I believe this was reported in #86 (but I didn't read that code in great detail).
I think there are more bugs along similar lines with other functions, but these came to my attention immediately because I encountered them in one of my own projects.
The first commit adds five new tests, four of which fail. The second commit fixes these tests.

Fix parent perms issues

---

lib/binding.js
lib/descriptor.js
lib/directory.js
lib/file.js
lib/filesystem.js
lib/index.js
lib/symlink.js
node/fs-6.3.0.js
test/helper.js
test/lib/binding.spec.js
test/lib/filesystem.spec.js

This adds `binding.realpath()` and adapts `binding.readlink()` and `binding.readdir()` so they can work with and without an `encoding` argument.
It also makes it so we rely on `require('constants')` instead of `process.binding('constants')`.
Fixes #137.

Fixes for Node 6.3

---

lib/binding.js
node/fs-6.3.0.js

This reduces the amount of manual patching done to the `fs` module.  The only significant part left is changing `const binding = process.binding('fs')` to `let binding = process.binding('fs')`.  It will be good to come up with an alternative there as well.

Reduce the manual fs module patching

---

lib/index.js
test/lib/index.spec.js

This makes it so `require()` calls work as expected (with the real `fs`) even after a mock is created.
Fixes #130.

Use the real fs module if in a require() call

---

readme.md

In some cases, not restoring the `fs` can produce side effects. If you are using [`nyc`](https://github.com/istanbuljs/nyc), for example, the reporting never ends. See istanbuljs/nyc#324

Add note about restoring the fs

---

node/fs-6.3.0.js
node/fs-7.0.0.js

Previously, calls to the deprecated method would throw here.

Remove calls to printDeprecation

---

lib/index.js
test/lib/index.spec.js

Addresses  #90 
* Useful for tests where you wish to make 'general' assertions over the
whole filesystem (e.g. security testing!)
* Also addresses an issue where the bindings were having 'extraneous' keys
left when the mock was restored. (Was unable to provide an isolated test
for this as the 'bindings' part is internal to the mock.

Exposes the root mocked filesytem if the mock is currently applied. (Fixes #90)

---

lib/binding.js
test/lib/binding.spec.js

Binding.open only follows a symlink once, so I fixed it so that it follows the symlink chain until the end.

Binding.open not following symlinks correctly

---

lib/binding.js

Node 7.7 changed the behavior of the `binding.{stat,lstat,fstat}` functions (see https://github.com/nodejs/node/pull/11522). This updates the binding functions used in mock-fs to match the new Node binding behavior, while still maintaining compatibility with old Node versions. The new behavior is detected when the second argument to `binding.{stat,lstat,fstat}` is a `Float64Array`, which would be an invalid argument for previous versions of the binding.
This commit does not add any tests because the existing tests were already broken by the Node update. Given that they're passing now, I think the behavior is already covered, but let me know if there are any tests I should add.

Update fs.stat(), fs.lstat(), and fs.fstat() for Node 7.7+ (fixes #197)

---

.travis.yml
lib/binding.js

This is still work in progress.
I managed to fix first issue - with stat function - but there is still a lot of tests failing.

Fixing test failures on node 8

---

.travis.yml
lib/binding.js
lib/filesystem.js
package-lock.json
package.json

This updates dev dependencies and stops caching `node_modules` on Travis and AppVeyor to get tests passing again.

Dev dependency updates

---

lib/binding.js
test/lib/binding.spec.js

Add error code check to readlink failure assertions.
Fixes #231

Throw ENOENT in readlink when item is missing

---

.travis.yml
lib/binding.js
lib/buffer.js
lib/file.js
package-lock.json
readme.md
test/lib/binding.spec.js
test/lib/file.spec.js
test/lib/index.spec.js

This addresses differences in stats handling between Node 8 and 10.  In addition it fixes `binding.access()` for symlinks (should throw for broken links) and avoids deprecated use of the `Buffer` constructor.
Fixes #236.

Fixes for Node 10

---

lib/binding.js
test/lib/binding.spec.js

We should throw an error when someone attempts to open a mocked directory. When we try to write to a directory currently, we don't do this properly and it causes a confusing error to be thrown.
*Node Version: v8.11.3*
```
const mockFS = require('mock-fs');
const fs = require('fs');
mockFS({
'/my/dir': {FOO: ''}
});
fs.writeFileSync('/my/dir', 'bar');
```
Results in 
```
TypeError: item.setContent is not a function
at Binding.<anonymous> (.../node_modules/mock-fs/lib/binding.js:442:12)
at maybeCallback (.../node_modules/mock-fs/lib/binding.js:53:17)
at Binding.open (.../node_modules/mock-fs/lib/binding.js:402:10)
...
```
Because we try to zero out the file content [here](https://github.com/tschaub/mock-fs/blob/master/lib/binding.js#L460-L465), but there is no content to modify on a …

Throw error when a directory is opened

---

lib/binding.js

fixes #250 
Does not provide support for DirEnt objects that were introduced in `10.10.0` with https://github.com/nodejs/node/commit/c7944a7a7bd92a446ea81d774ccad31e0e7c8a3f
But makes `fs.readdir` and `fs.readdirSync` work again.

rbinding.readdir can take anywhere from 2 to 4 arguments

---

readme.md

Hey,
I've recently found that Jest has been updating my snapshots without any notice. I figure out this only happens in tests using mockFs.

Add note about snapshot testing

---

.travis.yml
lib/binding.js
lib/error.js
lib/index.js
lib/item.js
test/lib/index.spec.js

I was terrified by the amount of refactor work in my own projects to remove mock-fs. So I jump in to fix mock-fs instead.
First, it passes all tests in nodejs v4, v6, v8, v10, v11 on Linux/Windows/macOS.
https://travis-ci.org/huochunpeng/mock-fs/builds/488264371
Note:
1. the failure of nodejs v10 and v11 on windows is probably due to a bug in nodejs itself. https://github.com/nodejs/node/issues/25913
2. removed v4 from travis-ci matrix. v4 works fine, but travis-ci windows box just had problem to install npm@3. BTW nodejs v4 is EOL anyway.
Tested on one of the projects I am working on, it finally can pass tests in nodejs v10. https://travis-ci.org/huochunpeng/cli/builds/488267193
**What's in this PR:**
It is used to capture the error details when calling fs synced methods. I am too lazy …

feat: support nodejs v10 and v11, support experimental fs.promises

---

lib/binding.js
lib/index.js

Changed strategy to prepatch fs-binding methods in order to bypass nodejs v10+'s direct binding method calling. As long as you do require('mock-fs') before using any fs method, the prepatch will work for nodejs v10+ readFile.
This new patch only works for ReadFileContext (used by fs.readFile), because its require is delayed (`if (!ReadFileContext) ReadFileContext = require('internal/fs/read_file_context')`)
Previous _writev patch is still required to bypass issue on WriteStream.
fixes #264, properly fixes #254

fix: prepatch fs-binding to improve support nodejs v10+ readFile

---

lib/binding.js
test/lib/binding.spec.js
test/lib/index.spec.js

This fix follows Nodejs behavior that silently passes if a recursive mkdir tries to create an existing folder.
closes #270

fix: fix recursive mkdir behavior on existing folder

---

.travis.yml
lib/binding.js
lib/item.js

fix: fix wrong time stamps on nodejs v12.10.0+

---

lib/binding.js

fs.promises.readFile triggers a list of different calls, the last one is "close". The "close" call has no return value, so we cannot check the existence of "val" to determine successfulness.
closes #278

fix: fix wrong promise rejection on some fs methods with no return value

---

lib/filesystem.js
test/lib/binding.spec.js

If you have a file: `/mock-dir/two.txt` and try to open `/mock-dir/two.txt/bogus-path`, you would get `item.getItem is not a function` Error due to `item` instance being a File, not a Directory.
This adds a fix to this by checking the instance of resolved `item` and throwing accordingly. 
This matches node's native behavior in such a case.

fix: throw ENOTDIR when trying to open an incorrect path (nested under existing file)

---

lib/binding.js
test/lib/fs.readdir.spec.js

Hi, I'm the maintainer of the [`fast-glob`](https://github.com/mrmlnc/fast-glob) package.
In my package, I try to use all possible ways to optimize the work with the file system. One of these ways is a `withFileTypes` option in the `fs.readdir` method. Unfortunately, this package does not support this option. So, this pull request implements support for this option.
This is a possible solution for the following issues:
* https://github.com/tschaub/mock-fs/issues/272
* https://github.com/mrmlnc/fast-glob/issues/246
My solution uses an internal implementation of the [`getDirents`](https://github.com/bengl/node/blob/f01ed4307e0dfa5f8a1189d9fd3fb93078814dda/lib/internal/fs/utils.js#L121) method from [`FSReqWrap`](https://github.com/bengl/node/blob/f01ed4307e0dfa5f8a1189d9fd3fb93078814dda/lib/f …

Implementing "withFileTypes" option for fs.readdir method

---

lib/binding.js
test/lib/fs.readFile.spec.js

fix: readFile on dir should fail EISDIR not EBADF

---

lib/descriptor.js
test/lib/descriptor.spec.js

The argument flags must include one of the following access modes:
O_RDONLY, O_WRONLY, or O_RDWR.  These request opening the file read-
only, write-only, or read/write, respectively.
O_RDONLY is 0, O_WRONLY is 1, O_RDWR is 2, the flags use 2 bits for 3 states: 0 (0b00) / 1 (0b01) / 2 (0b10), the 2 bits will never be 3 (0b11).
closes #288

fix: fix isRead check on file descriptor

---

lib/binding.js
test/helper.js
test/lib/fs.access.spec.js
test/lib/fs.chmod-fchmod.spec.js
test/lib/fs.chown-fchown.spec.js
test/lib/fs.copyFile.spec.js
test/lib/fs.link-symlink.spec.js
test/lib/fs.lstat.spec.js
test/lib/fs.mkdir.spec.js
test/lib/fs.open-close.spec.js
test/lib/fs.readdir.spec.js
test/lib/fs.readlink.spec.js
test/lib/fs.rename.spec.js
test/lib/fs.rmdir.spec.js
test/lib/fs.stat-fstat.spec.js
test/lib/fs.unlink.spec.js
test/lib/fs.utimes-futimes.spec.js

There is missing support of `"path <string> | <Buffer> | <URL>"` on many fs APIs.
closes #292

fix: support path input from Buffer on many fs APIs

---

lib/binding.js
test/lib/fs.readdir.spec.js

This PR adds access checks to `readdir`and `readdirSync` calls.
This should fix #294

fix: readdir should check for access rights, fixes #294

---

lib/bypass.js
lib/loader.js
readme.md
test/lib/index.spec.js

Bypass updates

---

.github/workflows/test.yml
lib/binding.js
lib/index.js

fix: fix the memory leak introduced in nodejs v10 patch

---

lib/index.js
test/lib/bypass.spec.js
test/lib/index.spec.js

All the patches now check same realBinding._mockedBinding. This should
fix the edge cases around the new feature bypass().
follows up #306

fix: synchronize patching binding/createWriteStream/cwd/chdir

---

.github/workflows/test.yml
lib/bypass.js
package-lock.json
test/lib/bypass.spec.js
test/lib/fs.access.spec.js
test/lib/fs.appendFile.spec.js
test/lib/fs.chmod-fchmod.spec.js
test/lib/fs.chown-fchown.spec.js
test/lib/fs.copyFile.spec.js
test/lib/fs.link-symlink.spec.js
test/lib/fs.lstat.spec.js
test/lib/fs.mkdir.spec.js
test/lib/fs.mkdtemp.spec.js
test/lib/fs.open-close.spec.js
test/lib/fs.read.spec.js
test/lib/fs.readFile.spec.js
test/lib/fs.readdir.spec.js
test/lib/fs.readlink.spec.js
test/lib/fs.realpath.spec.js
test/lib/fs.rename.spec.js
test/lib/fs.rmdir.spec.js
test/lib/fs.stat-fstat.spec.js
test/lib/fs.unlink.spec.js
test/lib/fs.utimes-futimes.spec.js
test/lib/fs.write.spec.js
test/lib/fs.writeFile.spec.js

I was planning to use this branch to implement fs.opendir, but it seems Nodejs would not open up access to internal binding `fs_dir` https://github.com/nodejs/node/issues/37746#issuecomment-798809618
This PR fixes mockfs.bypass support of Promise on old Nodejs versions where Promise.prototype.finally is not available. Also cleaned up the tests.

chore: cleanup tests and small fix on mockfs.bypass

---

lib/binding.js
lib/file.js
lib/item.js

Represent stdin, stdout, and stderr as files

---

lib/error.js

No idea why this did not fail in test/lib/binding.spec.js, a log of
uvBinding.errmap did yield the error map (maybe mocha patched it??).
It's very hard runtime error when using mock-fs 5.0.0-beta.1

fix: uvBinding.errmap is undefined in Nodejs v12+

---

lib/binding.js
lib/error.js
lib/filesystem.js
lib/index.js
lib/readfilecontext.js
test/lib/readfilecontext.js

Hoping to fix #332 with this
Large parts of the implementation in `readfilecontext.js` are copied straight from the Node.js internals. I'm assuming that is all fine as it's already called out in the licence file that parts of this project are copied from there.

Add support for Node.js v16.3.0+

---

lib/readfilecontext.js

Closes https://github.com/tschaub/mock-fs/issues/341
When collecting the prototype for `ReadFileContext` the original fsBinding.open should still be called so that FS read operations can be handled as usual.

Fix source of open FSREQCALLBACK handles 

---

lib/index.js

The `mock` method currently documents its `options` parameter as being required. This causes annoying code inspection errors in the IDE when passing only a single object as folows:
```js
mock({
"some-directory": {
"some-file.txt": "file content"
}
});
```
This change makes the parameter optional as intended.

Document mock options as an optional parameter

---

.github/workflows/test.yml
lib/item.js

fix: support bigint stats in Nodejs v18.7+

---

lib/binding.js

this is a little fix for for an typeError i got with jest on node 16.7.0

fix: TypeError: Cannot convert  to a BigInt

---

lib/binding.js
test/lib/binding.spec.js
test/lib/item.spec.js

This PR comes to fix an error with the `access` function what does not implement a check for a root user. To fix this I'm reusing the logic already implemented in `canRead`, `canWrite` and `canExecute` functions (I've also added tests for those cases in `item.spec.js`).
I've added test for the error case to `bindings.spec.js`.
P.S. Since, there is no mocking library currently used in the project, so i've used a manual method to mock `process.getuid` and `process.getgid` functions which can easily be replaced by any mocking library.

fix: fix EACCES error on access by root user

---

.github/workflows/test.yml
readme.md

Node 12 and 14 are no longer available in GitHub actions for platform darwin and architecture arm64.

Stop testing on Node 12 and 14

---

test/lib/fs.appendFile.spec.js
test/lib/fs.chmod-fchmod.spec.js
test/lib/fs.copyFile.spec.js
test/lib/fs.link-symlink.spec.js
test/lib/fs.lstat.spec.js
test/lib/fs.mkdir.spec.js
test/lib/fs.mkdtemp.spec.js
test/lib/fs.open-close.spec.js
test/lib/fs.read.spec.js
test/lib/fs.readFile.spec.js
test/lib/fs.readdir.spec.js
test/lib/fs.readlink.spec.js
test/lib/fs.realpath.spec.js
test/lib/fs.rename.spec.js
test/lib/fs.rmdir.spec.js
test/lib/fs.stat-fstat.spec.js
test/lib/fs.unlink.spec.js
test/lib/fs.utimes-lutimes-futimes.spec.js
test/lib/fs.write.spec.js
test/lib/fs.writeFile.spec.js

While working on
https://github.com/tschaub/mock-fs/blob/main/changelog.md#400 I noticed
that tests would timeout when some assertions failed because done was
never called.
```
promise.then(() => {
assert(false)
done()
}, done)
```
The issue is that `then` will only call one of it's two callbacks. The
onRejected function is not called when onFulfilled throws an error.
Switching to `.catch(done)` guarnatees the a rejected promise chain
marks the test as completed.

fix timeout in failing test

---

.github/workflows/test.yml
lib/binding.js
lib/descriptor.js
lib/filesystem.js
test/lib/bypass.spec.js
test/lib/index.spec.js

This includes @andrewnicols's changes from https://github.com/tschaub/mock-fs/pull/381
All unit tests pass on node 20 (and 22) 
I have not written any new tests, or checked that any new APIs work correctly. 
This at-least partially fixes https://github.com/tschaub/mock-fs/issues/384. I tested these changes in an application that was failing with mock-fs 5.2.0 and node 20

Fix tests on node 20

---

.github/dependabot.yml
.github/workflows/test.yml
package-lock.json
test/lib/fs.link-symlink.spec.js
test/lib/fs.open-close.spec.js
test/lib/fs.readFile.spec.js
test/lib/fs.rmdir.spec.js
test/lib/readfilecontext.spec.js

This removes conditions and tests that only applied to untested Node versions (< 16).

Remove conditions for untested versions

---

lib/binding.js
test/lib/fs.exists.spec.js

Node's `fs.exists()` [never throws](https://github.com/nodejs/node/blob/v22.11.0/lib/fs.js#L273-L274). And the `fs.existsSync()` is called with `false` [on any errors](https://github.com/nodejs/node/blob/v22.11.0/lib/fs.js#L255-L257).
Fixes #400.

Ignore errors in fs.exists

---

lib/binding.js
test/lib/encoding.spec.js

The writeFileUtf8 binding used by node 20 was not correctly encoding strings as utf8, and recording the file length as
String.prototype.length, which returns number of utf-16 code units.
If you wrote a string containing code points with a different number of utf-8 code units than utf-16 code units, then read the file back the returned string would be truncated by the difference in the number of code units.

fix: encoding utf8 strings in node 20

---

test/lib/fs.createWriteStream.spec.js

This adds a test demonstrating the use of `fs.createWriteStream()` with the append flag.
See #411.

Add test showing `fs.createWriteStream()` with append
