lib/index.js, package.json
This allows a more fine grained control of the used fs module for future upcoming versions.
Fixes #17.
=> Semver versioning support added. Closed #17

.travis.yml, appveyor.yml, lib/index.js, node/fs-2.0.0.js
I haven't made any changes since all the tests passed.
I just added a new file and version. Let me know if you want a different name on the file!
=> Added io.js 2.0.0 support

readme.md
Fixes a bit of language in the readme.
=> Minor language tweak

.travis.yml, lib/index.js, node/fs-3.0.0.js
This PR is attended to fix #54.
=> Add support for io.js 3.x

lib/index.js, package.json, test/helper.js, test/integration/filecount.js, test/lib/binding.spec.js
This updates project dependencies.  New linter.  Less lint.
=> Update dependencies, remove lint

.travis.yml, appveyor.yml
This updates the Travis and AppVeyor configurations.
=> CI updates

appveyor.yml, package.json
This updates all dependencies.
=> Dependency updates

package.json
Update linter config to work with ESLint v2.
=> Update ESLint config

.gitignore, .travis.yml, lib/index.js, node/fs-7.0.0.js
New version of node has been released: Node v7
According to [change log](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md) it introduces following changes to file system:
> - A process warning is emitted if a callback is not passed to async file system methods [#7897](https://github.com/nodejs/node/pull/7897).
Actual diff:
=> Node v7 support

package.json, readme.md
This adds docs about upcoming breaking changes.
=> Document breaking changes in the upcoming 4.0.0-beta.1 release

lib/filesystem.js, test/lib/filesystem.spec.js
This is a rebased version of @mutantcornholio's work in #218.
Closes #218.
=> Throw error if item content is invalid

readme.md
This is a rebased version of @denar90's change in #214.
Closes #214.
=> Update readme to use const

lib/error.js
=> Add path to errors when it exists

lib/binding.js
Thanks @tomhughes for the fix.
Replaces #240.  See #238.
=> Stat fixes for 10.5

lib/binding.js, test/lib/binding.spec.js
=> Add tests for reading and writing using Uint8Array

package-lock.json, package.json
This resolves a warning from `npm audit`.
=> Remove dev dependency on minimatch

benchmarks/read-integration-mock.js, benchmarks/read-integration-real.js, benchmarks/read-mock.js, benchmarks/read-real.js, benchmarks/write-integration-mock.js, benchmarks/write-integration-real.js, benchmarks/write-mock.js, benchmarks/write-real.js, lib/binding.js, lib/descriptor.js, lib/directory.js, lib/error.js, lib/file.js, lib/filesystem.js, lib/index.js, lib/item.js, lib/symlink.js, package-lock.json, package.json, test/helper.js, test/integration/filecount.js, test/integration/filecount.spec.js, test/lib/binding.spec.js, test/lib/descriptor.spec.js, test/lib/directory.spec.js, test/lib/file.spec.js, test/lib/filesystem.spec.js, test/lib/index.spec.js, test/lib/item.spec.js
This updates the dev dependencies and modifies syntax to match the new linter rules.
=> Update dev dependencies and remove lint

package-lock.json
This updates dependencies of dev dependencies.
=> Transitive dependency updates

.github/workflows/publish.yml, package.json, tasks/next-dev-version.js
This adds a new publish workflow to publish `dev` tagged releases for each commit to the default branch.
=> New workflow to publish dev tagged releases

package-lock.json
=> Dev dependency update

test/lib/index.spec.js
=> remove disabled tests for mock.fs

lib/binding.js, test/lib/fs.link-symlink.spec.js
=> Add test and fix exists behaviour for relative symlinks
